name: Daily Commit

on:
  schedule:
    # This cron expression runs the workflow once per day at 9 AM UTC
    - cron: '0 9 * * *'  # Set the specific hours and minutes as required
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    # Step to check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step to configure Git with your email and name
    - name: Set up Git identity
      run: |
        git config --global user.email "23f2004941@ds.study.iitm.ac.in"
        git config --global user.name "23f2004941@ds.study.iitm.ac.in"

    # Step to create a daily commit
    - name: Make daily commit by 23f2004941@ds.study.iitm.ac.in
      run: |
        echo "Daily commit by 23f2004941@ds.study.iitm.ac.in" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
